server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: auth-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
