server:
  port: 18081

spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: auth-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jwt:
    access-token-expiration: 3600000      # 1 час
    refresh-token-expiration: 86400000    # 24 часа
    secret: your-super-secret-key
