services:

  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data


  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres-inventory:
    image: postgres:15
    container_name: postgres-inventory
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_inventory_data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  redpanda:
    image: redpandadata/redpanda:v23.3.10
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    depends_on:
      - redpanda
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://redpanda:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres-auth
      - redpanda
    ports:
      - "8081:8081"

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - postgres-user
      - redpanda
    ports:
      - "8082:8082"

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - mongo
      - redpanda
    ports:
      - "8083:8083"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      - postgres-inventory
      - redpanda
    ports:
      - "8084:8084"

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - postgres-order
      - redpanda
    ports:
      - "8085:8085"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - mongo
      - redpanda
    ports:
      - "8086:8086"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - auth-service
      - user-service
      - product-service
      - inventory-service
      - order-service
      - notification-service
    ports:
      - "8080:8080"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"


volumes:
  postgres_auth_data:
  postgres_user_data:
  postgres_inventory_data:
  postgres_order_data:
  mongo_data:

