server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/products/**

        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/orders/**

        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
