server:
  port: 18080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:18081
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://user-service:18082
          predicates:
            - Path=/users/**

        - id: product-service
          uri: http://product-service:18083
          predicates:
            - Path=/products/**

        - id: inventory-service
          uri: http://inventory-service:18084
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: http://order-service:18085
          predicates:
            - Path=/orders/**

        - id: notification-service
          uri: http://notification-service:18086
          predicates:
            - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
